name: Build MKW-SP

on: 
  push:
    paths-ignore:
      - 'tools/**'
      - '.github/workflows/build_tools.yml'
  pull_request:
    paths-ignore:
      - 'tools/**'
      - '.github/workflows/build_tools.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DEVKITPPC: opt/devkitpro/devkitPPC
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache DevkitPPC
        id: cache-1
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-cache-dkp-r41-2
      - name: Download devkitPPC
        if: steps.cache-1.outputs.cache-hit != 'true'
        run: | 
          mkdir cache && cd cache
          wget "https://wii.leseratte10.de/devkitPro/devkitPPC/r41%20%282022-05-31%29/devkitPPC-r41-2-linux_x86_64.pkg.tar.xz"
          cd ..
      - name: Extract devkitPPC
        run: tar -xf cache/devkitPPC-r41-2-x86_64.pkg.tar.xz
      - name: Install ninja
        run: sudo apt install ninja-build
      - name: Install protoc
        run: sudo apt install protobuf-compiler
      - name: Install PyPy
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy-3.8'
      - name: Install json5
        run: pip install json5
      - name: Install pyelftools
        run: pip install pyelftools
      - name: Install itanium_demangler
        run: pip install itanium_demangler
      - name: Install protobuf
        run: pip install protobuf
      - name: Configure ninja
        run: ./configure.py
      - name: Compile
        run: ninja
      - name: Upload result
        uses: actions/upload-artifact@v3
        with: 
          name: mkw-sp
          path: out
